### ISSUE TITLE
Change repo name to `ubna-field` or something similar?

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/ubna-field#101]
I am wondering if we should change the repo name so that we can easily search for `ubna` to find this repo -- may be it is just me, that i get confused on what keywords to use  in the search.

**Comment by aditya-uw** [comment]
@leewujung I think this is a good idea. I just noticed the mic array repository is `ubna-bat-array` and I like the `ubna` keyword too.

**Comment by leewujung** [comment]
Ok! I'll make that change then.
